## 데이터 정보

- df1: 장애유형별고용현황
- df2: 장애인고용연구보고서
- df3: 장애인구인정보
- df4: 장애인구직자현황
- df5: 장애인취업정보

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

%matplotlib inline

In [4]:
# 한글폰트 사용을 위해 설치, 아래 모듈을 설치하고 불러오면 별도의 한글폰트 설정이 필요 없습니다.
!pip install koreanize-matplotlib

import koreanize_matplotlib

Requirement already satisfied: koreanize-matplotlib in /Users/yeon/anaconda3/lib/python3.11/site-packages (0.1.1)
Requirement already satisfied: matplotlib in /Users/yeon/anaconda3/lib/python3.11/site-packages (from koreanize-matplotlib) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)

In [5]:
import matplotlib.pyplot as plt
from IPython.display import set_matplotlib_formats

# Mac 의 한글 폰트 설정
plt.rc('font', family='AppleGothic')
plt.rc('axes', unicode_minus=False)

# 폰트가 선명하게 보이기 위해 - 그래프에 retina display 적용
%config InlineBackend.figure_format = 'retina'

In [8]:
df1 = pd.read_csv('장애유형별고용현황.csv', encoding='euc-kr')
df1

,연번,구분,계,지체,뇌병변,시각,청각,언어,지적,정신,자폐성,신장,심장,호흡기,간,안면,장루요루,뇌전증,국가유공
0,1,국가및지자체(중앙행정기관),1923,1084,103,237,178,19,82,29,9,53,7,1,18,8,4,8,83
1,2,국가및지자체(헌법기관),87,55,0,13,3,1,6,1,2,1,0,0,1,0,0,0,4
2,3,국가및지자체(지방자치단체),11388,5317,1068,958,876,79,1837,452,162,356,32,40,56,19,54,51,31
3,4,국가및지자체(교육청),4858,1765,264,368,355,36,1552,74,216,103,10,9,17,3,15,12,59
4,5,공공기관(공기업),5138,2421,233,588,215,32,119,34,33,153,19,6,47,13,16,16,1193
5,6,공공기관(준정부기관),4615,2190,281,554,262,37,331,71,47,188,27,13,28,17,13,8,548
6,7,공공기관(기타공공기관),5052,2779,296,594,290,35,288,107,50,219,19,14,25,11,21,6,298
7,8,공공기관(지방공기업),2813,1537,97,306,163,23,88,19,5,77,9,4,25,7,13,2,438
8,9,공공기관(출자·출연법인),1376,699,91,149,89,3,165,22,18,37,4,4,14,1,5,5,70
9,10,민간기업(100인미만),19391,9716,634,1539,1958,155,3278,373,306,402,28,45,114,32,52,31,728
10,11,민간기업(100~200인미만),25958,13061,1106,2471,2542,221,3714,469,347,626,52,51,129,42,58,42,1027
11,12,민간기업(200~300인미만),14781,7452,656,1354,1478,113,2188,286,251,334,19,20,71,22,39,22,476
12,13,민간기업(300~500인미만),16468,7736,679,1662,1737,110,2552,286,368,371,34,23,76,26,36,20,752
13,14,민간기업(500~1000인미만),20228,9398,855,2126,2173,136,3196,456,436,427,29,31,87,30,52,28,768
14,15,민간기업(1000인이상),55721,25864,2219,6143,4930,324,9138,978,1106,1385,98,74,261,130,109,63,2899

In [14]:
df2 = pd.read_csv('장애인고용연구보고서.csv', encoding='cp949')
df2

       년도  연번  과제구분                                        연구과제명
0    2013   1  기본과제                장애인 고용촉진 및 직업재활 기금의 효율적 운영 방안
1    2013   2  기본과제                      2013년 장애인고용기업의 추가비용 조사
2    2013   3  기본과제        정신장애인 고용유지율 향상을 위한 공공·민간 연계사업에 관한 연구
3    2013   4  기본과제                              워크투게더센터사업 발전방안
4    2013   5  기본과제                                장애학생 취업지원 방안
..    ...  ..   ...                                          ...
298  2022  19  수시과제                      한국 독일 프랑스 장애인고용정책 사례 비교
299  2022  20  위탁과제               장애인 고용촉진 및 직업재활 기본계획 평가 및 향후과제
300  2022  21  위탁과제                         2022년 장애인고용기업 추가비용조사
301  2022  22  위탁과제  장애인구 및 4차산업 변화를 고려한 민간부문 장애인 의무고용률 설정 방안 연구
302  2022  23  위탁과제                     IT 산업 장애인 직업능력개발 훈련수요 조사

[303 rows x 4 columns]

In [10]:
df3 = pd.read_csv('장애인구인정보.csv', encoding='euc-kr')
df3

,연번,구인신청일자,모집기간,사업장명,모집직종,고용형태,임금형태,임금,입사형태,요구경력,요구학력,전공계열,요구자격증,사업장 주소,기업형태,담당기관,등록일,연락처
0,1,2023-11-30,2023-11-30~2023-12-31,현대아라아트,공예 보조원(공예견습생),시간제,시급,9620,무관,0년개월,무관,NaN,,"인천광역시 미추홀구 경인로 372 (주안동, 포레나 미추홀) B2층 2101호",중소,인천지사,2023-11-30,1588-1819
1,2,2023-11-30,2023-11-30~2023-12-05,하나증권,사무 보조원,계약직,월급,1800000,신입,무관,무관,NaN,,서울특별시 영등포구 의사당대로 82 (여의도동),대기업,서울남부지사,2023-11-30,1588-1819
2,3,2023-11-30,2023-11-30~2023-12-31,의성군청,"사무 보조원(국가 및 자치단체, 공공기관)",계약직,월급,2060740,무관,무관,무관,NaN,,경상북도 의성군 의성읍 군청길 31 (후죽리),"공사,공공",경북지사,2023-11-30,1588-1819
3,4,2023-11-30,2023-11-30~2024-01-31,케이티네크워크(주),전기·전자 분야 단순 종사원,상용직,시급,9620,무관,0년개월,무관,NaN,,광주광역시 광산구 하남산단9번로 196 (도천동),중소,광주지역본부,2023-11-30,1588-1819
4,5,2023-11-30,2023-11-30~2024-01-31,(주)모아종합건설,주차 관리·안내원,상용직,시급,9620,무관,0년개월,무관,NaN,,광주광역시 북구 서암대로 205 (중흥동),중소,광주지역본부,2023-11-30,1588-1819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,1112,2023-11-01,2023-11-01~2023-12-31,신안군청,일반 간호사,상용직,월급,2100000,무관,무관,무관,NaN,,"전라남도 신안군 압해읍 천사로 1004 (신장리), 신안군청","공사,공공",전남지사,2023-11-01,1588-1819
1112,1113,2023-11-01,2023-11-06~2023-12-31,주식회사 손지음,"제품 포장원(섬유, 전기전자, 식품 제외)",상용직,시급,9620,경력,3년개월,무관,NaN,,경기도 김포시 통진읍 고척로 237-5 주식회사 손지음,중소,경기북부지사,2023-11-13,1588-1819
1113,1114,2023-11-01,2023-11-01~2023-12-31,강원도 고성군청,국가·지방행정 사무원,상용직,월급,2472655,무관,무관,무관,NaN,,"강원도 고성군 간성읍 고성중앙길 9 (하리), 고성군청","공사,공공",강원지사,2023-11-01,1588-1819
1114,1115,2023-11-01,2023-11-01~2023-12-31,한국생명공학연구원,"사무 보조원(국가 및 자치단체, 공공기관)",계약직,월급,1876000,무관,무관,무관,NaN,,대전광역시 유성구 과학로 125 (어은동),중소,충북지사,2023-11-01,1588-1819
1115,1116,2023-11-01,2023-11-01~2023-11-06,(주)신영와코루,마케팅·광고·홍보·상품기획 사무원,상용직,연봉,32000000,무관,무관,대졸,섬유공학,,서울특별시 금천구 가산디지털1로 104 1층,중소,서울남부지사,2023-11-01,1588-1819

In [15]:
df4 = pd.read_csv('장애인구직자현황.csv', encoding='euc-kr')
df4

,연번,구직등록일,연령,희망지역,희망직종,희망임금,장애유형,중증여부,기관분류
0,1,2022-01-01,39,경기 수원시,"기타 서비스 단순종사원(사우나,찜질방 정리원 등)",(시급)8720,지적장애,중증,공단
1,2,2022-01-01,39,서울특별시,사무 보조원(일반사업체),(시급)9160,지체장애,경증,공단
2,3,2022-01-01,57,충남 당진시,사무 보조원(공공기관),(시급)9160,지체장애,경증,공단
3,4,2022-01-01,40,충남 서산시,음료 조리사(바리스타 포함),(시급)9160,뇌병변장애,경증,공단
4,5,2022-01-01,35,충남 천안시 서북구,자동조립라인 조작원,(시급)9160,청각장애,중증,공단
...,...,...,...,...,...,...,...,...,...
34486,34487,2022-12-30,19,경기 수원시,"인쇄, 목재, 가구 및 기타 제조 분야 단순 종사원",(시급)9160,지적장애,중증,공단
34487,34488,2022-12-30,28,경기 부천시,"기타 서비스 단순종사원(사우나,찜질방 정리원 등)",(시급)9160,지적장애,중증,공단
34488,34489,2022-12-30,36,경북 포항시,직업 운동선수,(시급)9160,지적장애,중증,공단
34489,34490,2022-12-30,43,서울 영등포구,사회복지사(사회복지시설),(시급)9160,청각장애,중증,공단
34490,34491,2022-12-30,47,인천 부평구,사무 보조원(공공기관),(시급)9160,뇌병변장애,중증,공단

In [16]:
df5 = pd.read_csv('장애인취업정보.csv', encoding='euc-kr')
df5

        순번        취업일자    연령  장애유형 중증여부    근무지역    취업직종대분류
0      1.0  2022-06-01  26.0  정신장애   중증  경기 용인시  경영·행정·사무직
1      2.0  2022-01-01  28.0  지적장애   중증  충북 영동군  경영·행정·사무직
2      3.0  2022-01-01  19.0  지적장애   중증  충북 영동군  경영·행정·사무직
3      4.0  2022-01-01  22.0  지적장애   중증  충북 영동군  경영·행정·사무직
4      5.0  2022-01-01  23.0  지적장애   중증  충북 영동군  경영·행정·사무직
...    ...         ...   ...   ...  ...     ...        ...
46573  NaN         NaN   NaN   NaN  NaN     NaN        NaN
46574  NaN         NaN   NaN   NaN  NaN     NaN        NaN
46575  NaN         NaN   NaN   NaN  NaN     NaN        NaN
46576  NaN         NaN   NaN   NaN  NaN     NaN        NaN
46577  NaN         NaN   NaN   NaN  NaN     NaN        NaN

[46578 rows x 7 columns]