In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

!pip install koreanize-matplotlib
import koreanize_matplotlib

import matplotlib.pyplot as plt
from IPython.display import set_matplotlib_formats

%matplotlib inline

# Mac 의 한글 폰트 설정
plt.rc('font', family='AppleGothic')
plt.rc('axes', unicode_minus=False)

# 폰트가 선명하게 보이기 위해 - 그래프에 retina display 적용
%config InlineBackend.figure_format = 'retina'

Requirement already satisfied: koreanize-matplotlib in /Users/yeon/anaconda3/lib/python3.11/site-packages (0.1.1)
Requirement already satisfied: matplotlib in /Users/yeon/anaconda3/lib/python3.11/site-packages (from koreanize-matplotlib) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from matplotlib->koreanize-matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/yeon/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)

## 장애인 구인, 구직정보 csv파일 보이기

In [3]:
df3 = pd.read_csv('장애인구인정보.csv', encoding='euc-kr')
df3
# 모집직종, 임금형태, 임금, 요구경력, 사업장명, 사업장 주소, 기업형태 필요 (등록일 날리자 2023 데이터활용)
# 희망 연령이 없어서 직종형태에 따라 우리가 좀 나눠야할 수도?

,연번,구인신청일자,모집기간,사업장명,모집직종,고용형태,임금형태,임금,입사형태,요구경력,요구학력,전공계열,요구자격증,사업장 주소,기업형태,담당기관,등록일,연락처
0,1,2023-11-30,2023-11-30~2023-12-31,현대아라아트,공예 보조원(공예견습생),시간제,시급,9620,무관,0년개월,무관,NaN,,"인천광역시 미추홀구 경인로 372 (주안동, 포레나 미추홀) B2층 2101호",중소,인천지사,2023-11-30,1588-1819
1,2,2023-11-30,2023-11-30~2023-12-05,하나증권,사무 보조원,계약직,월급,1800000,신입,무관,무관,NaN,,서울특별시 영등포구 의사당대로 82 (여의도동),대기업,서울남부지사,2023-11-30,1588-1819
2,3,2023-11-30,2023-11-30~2023-12-31,의성군청,"사무 보조원(국가 및 자치단체, 공공기관)",계약직,월급,2060740,무관,무관,무관,NaN,,경상북도 의성군 의성읍 군청길 31 (후죽리),"공사,공공",경북지사,2023-11-30,1588-1819
3,4,2023-11-30,2023-11-30~2024-01-31,케이티네크워크(주),전기·전자 분야 단순 종사원,상용직,시급,9620,무관,0년개월,무관,NaN,,광주광역시 광산구 하남산단9번로 196 (도천동),중소,광주지역본부,2023-11-30,1588-1819
4,5,2023-11-30,2023-11-30~2024-01-31,(주)모아종합건설,주차 관리·안내원,상용직,시급,9620,무관,0년개월,무관,NaN,,광주광역시 북구 서암대로 205 (중흥동),중소,광주지역본부,2023-11-30,1588-1819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,1112,2023-11-01,2023-11-01~2023-12-31,신안군청,일반 간호사,상용직,월급,2100000,무관,무관,무관,NaN,,"전라남도 신안군 압해읍 천사로 1004 (신장리), 신안군청","공사,공공",전남지사,2023-11-01,1588-1819
1112,1113,2023-11-01,2023-11-06~2023-12-31,주식회사 손지음,"제품 포장원(섬유, 전기전자, 식품 제외)",상용직,시급,9620,경력,3년개월,무관,NaN,,경기도 김포시 통진읍 고척로 237-5 주식회사 손지음,중소,경기북부지사,2023-11-13,1588-1819
1113,1114,2023-11-01,2023-11-01~2023-12-31,강원도 고성군청,국가·지방행정 사무원,상용직,월급,2472655,무관,무관,무관,NaN,,"강원도 고성군 간성읍 고성중앙길 9 (하리), 고성군청","공사,공공",강원지사,2023-11-01,1588-1819
1114,1115,2023-11-01,2023-11-01~2023-12-31,한국생명공학연구원,"사무 보조원(국가 및 자치단체, 공공기관)",계약직,월급,1876000,무관,무관,무관,NaN,,대전광역시 유성구 과학로 125 (어은동),중소,충북지사,2023-11-01,1588-1819
1115,1116,2023-11-01,2023-11-01~2023-11-06,(주)신영와코루,마케팅·광고·홍보·상품기획 사무원,상용직,연봉,32000000,무관,무관,대졸,섬유공학,,서울특별시 금천구 가산디지털1로 104 1층,중소,서울남부지사,2023-11-01,1588-1819

In [4]:
# 구인정보
selected_columns = df3[['모집직종', '임금형태', '임금', '요구경력', '기업형태']]
df3_selected = selected_columns
df3_selected

                         모집직종 임금형태        임금  요구경력   기업형태
0               공예 보조원(공예견습생)   시급      9620  0년개월     중소
1                      사무 보조원   월급   1800000    무관    대기업
2     사무 보조원(국가 및 자치단체, 공공기관)   월급   2060740    무관  공사,공공
3             전기·전자 분야 단순 종사원   시급      9620  0년개월     중소
4                   주차 관리·안내원   시급      9620  0년개월     중소
...                       ...  ...       ...   ...    ...
1111                   일반 간호사   월급   2100000    무관  공사,공공
1112  제품 포장원(섬유, 전기전자, 식품 제외)   시급      9620  3년개월     중소
1113              국가·지방행정 사무원   월급   2472655    무관  공사,공공
1114  사무 보조원(국가 및 자치단체, 공공기관)   월급   1876000    무관     중소
1115       마케팅·광고·홍보·상품기획 사무원   연봉  32000000    무관     중소

[1116 rows x 5 columns]

In [5]:
df4 = pd.read_csv('장애인구직자현황.csv', encoding='euc-kr')
df4
# 연령, 희망지역, 희망직종, 희망임금, 장애유형, 중증여부, 기관분류 (구직등록일 날리자 2022년 1년 활용)

,연번,구직등록일,연령,희망지역,희망직종,희망임금,장애유형,중증여부,기관분류
0,1,2022-01-01,39,경기 수원시,"기타 서비스 단순종사원(사우나,찜질방 정리원 등)",(시급)8720,지적장애,중증,공단
1,2,2022-01-01,39,서울특별시,사무 보조원(일반사업체),(시급)9160,지체장애,경증,공단
2,3,2022-01-01,57,충남 당진시,사무 보조원(공공기관),(시급)9160,지체장애,경증,공단
3,4,2022-01-01,40,충남 서산시,음료 조리사(바리스타 포함),(시급)9160,뇌병변장애,경증,공단
4,5,2022-01-01,35,충남 천안시 서북구,자동조립라인 조작원,(시급)9160,청각장애,중증,공단
...,...,...,...,...,...,...,...,...,...
34486,34487,2022-12-30,19,경기 수원시,"인쇄, 목재, 가구 및 기타 제조 분야 단순 종사원",(시급)9160,지적장애,중증,공단
34487,34488,2022-12-30,28,경기 부천시,"기타 서비스 단순종사원(사우나,찜질방 정리원 등)",(시급)9160,지적장애,중증,공단
34488,34489,2022-12-30,36,경북 포항시,직업 운동선수,(시급)9160,지적장애,중증,공단
34489,34490,2022-12-30,43,서울 영등포구,사회복지사(사회복지시설),(시급)9160,청각장애,중증,공단
34490,34491,2022-12-30,47,인천 부평구,사무 보조원(공공기관),(시급)9160,뇌병변장애,중증,공단

In [6]:
# 구직자 정보
selected_columns2 = df4[['연령','희망직종', '장애유형', '중증여부']]
df4_selected = selected_columns2
df4_selected

       연령                          희망직종   장애유형 중증여부
0      39   기타 서비스 단순종사원(사우나,찜질방 정리원 등)   지적장애   중증
1      39                 사무 보조원(일반사업체)   지체장애   경증
2      57                  사무 보조원(공공기관)   지체장애   경증
3      40               음료 조리사(바리스타 포함)  뇌병변장애   경증
4      35                    자동조립라인 조작원   청각장애   중증
...    ..                           ...    ...  ...
34486  19  인쇄, 목재, 가구 및 기타 제조 분야 단순 종사원   지적장애   중증
34487  28   기타 서비스 단순종사원(사우나,찜질방 정리원 등)   지적장애   중증
34488  36                       직업 운동선수   지적장애   중증
34489  43                 사회복지사(사회복지시설)   청각장애   중증
34490  47                  사무 보조원(공공기관)  뇌병변장애   중증

[34491 rows x 4 columns]

## df3_selected : 필요한 장애인 구인정보
## df4_selected : 필요한 장애인 구직정보

- (구인정보) '사업장 주소'랑 (구직자정보) '희망지역'은 가까운 곳으로 일단 쳐내고 가기
- 위치는 일단 열에서 뺄게요

## 📎 모집직종 & 희망직종 유사도 측정

- 이걸로 유사도 측정을 하고, 추천해준 다음, user_info를 구인하는 곳에 보낼 수 있도록 하는 시스템 제안
- 코사인, 자카드, 유클리디안 등의 유사도 측정 거리를 여러개 해보고, 가장 약간 경직도가 적당하는 것을 선정? 혹은 다른 방법으로 선정

In [7]:
# df3_selected.head()
job_posting = df3_selected['모집직종']
job_posting.head()

0              공예 보조원(공예견습생)
1                     사무 보조원
2    사무 보조원(국가 및 자치단체, 공공기관)
3            전기·전자 분야 단순 종사원
4                  주차 관리·안내원
Name: 모집직종, dtype: object

In [8]:
type(job_posting)

pandas.core.series.Series

In [9]:
# df4_selected.head()
user_info = df4_selected['희망직종']
user_info.head()

0    기타 서비스 단순종사원(사우나,찜질방 정리원 등)
1                  사무 보조원(일반사업체)
2                   사무 보조원(공공기관)
3                음료 조리사(바리스타 포함)
4                     자동조립라인 조작원
Name: 희망직종, dtype: object

## (1) 코사인 유사도 측정 
- (텍스트 -> 벡터변환)
- 여러 컬럼으로 구성된 df의 각 행을 하나의 텍스트로 합치고, 이를 벡터로 변환
- 주어진 df에서 코사인 유사도를 측정하는 코드

In [10]:
# 필요한 라이브러리 불러오기
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# 사용자로부터 입력받을 희망 직종은 user_input으로 가정
user_input = "사무 보조"

# 직무 포스팅과 사용자 정보 추출
job_postings = df3_selected['모집직종'].fillna('')
user_info = df4_selected['희망직종'].fillna(user_input)

# Combine job_postings and user_info into a list of documents
documents = job_postings.tolist() + user_info.tolist()

# CountVectorizer를 사용하여 텍스트를 토큰 수의 행렬로 변환
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# 직무 포스팅과 사용자 정보 간의 코사인 유사도 계산
cosine_similarities = cosine_similarity(X)

# 사용자 입력에 대한 코사인 유사도 값 찾기
user_input_index = len(job_postings) + user_info.index[-1]
user_similarity = cosine_similarities[user_input_index]


# 유사도가 높은 job_posting 추천
print("Length of user_similarity:", len(user_similarity))
print("Length of df3_selected:", len(df3_selected))

print("사용자에게 추천하는 직무 포스팅:")
for i, job in enumerate(recommended_jobs, start=1):
    print(f"{i}. {job}")

Length of user_similarity: 35607
Length of df3_selected: 1116
사용자에게 추천하는 직무 포스팅:

NameError: name 'recommended_jobs' is not defined

In [11]:
recommended_job_indices = user_similarity.argsort()[:-6:-1]  # 상위 5개 추천
print("Recommended job indices:", recommended_job_indices)

# Add a check to ensure indices are within bounds
valid_indices = recommended_job_indices[recommended_job_indices < len(df3_selected)]
recommended_jobs = df3_selected.iloc[valid_indices]['모집직종']

# 유사도가 높은 상위 10개와 하위 10개 job_posting 추천
top_recommendations = user_similarity.argsort()[:-11:-1]  # 상위 10개 추천
bottom_recommendations = user_similarity.argsort()[:10]  # 하위 10개 추천

print("상위 10개 유사한 직무 포스팅:")
for i, idx in enumerate(top_recommendations, start=1):
    job_description = df3_selected.iloc[idx]['모집직종']
    cosine_value = user_similarity[idx]
    print(f"{i}. 직무 포스팅: {job_description}")
    print(f"   코사인 유사도: {cosine_value}\n")

print("하위 10개 유사한 직무 포스팅:")
for i, idx in enumerate(bottom_recommendations, start=1):
    job_description = df3_selected.iloc[idx]['모집직종']
    cosine_value = user_similarity[idx]
    print(f"{i}. 직무 포스팅: {job_description}")
    print(f"   코사인 유사도: {cosine_value}\n")

Recommended job indices: [35606 16030 16055 16054 16043]
상위 10개 유사한 직무 포스팅:

IndexError: single positional indexer is out-of-bounds

In [ ]:
# 시각화

import seaborn as sns
import matplotlib.pyplot as plt

# 시각화를 위해 데이터프레임 생성
cosine_similarity_df = pd.DataFrame(cosine_similarities, columns=job_postings.tolist() + user_info.tolist(),
                                    index=job_postings.tolist() + user_info.tolist())

# 히트맵 그리기
plt.figure(figsize=(12, 10))
sns.heatmap(cosine_similarity_df, cmap='coolwarm', annot=False)
plt.title('코사인 유사도 히트맵')
plt.show()

## (2) 유저로부터 input받음 ->  job_posting 상하위 10개 출력

- (여기서 든 생각)
- 그래서 자신과 같은 장애를 가진 사람들이 어떤 직무로 구직을 했는지 알려주는 시스템도 필요함

In [ ]:
# 사용자 정보 입력 받기
user_input = input("당신의 직무 선호도를 입력하세요: ")

# 입력된 정보를 텍스트로 변환하여 documents에 추가
documents.append(user_input)

# CountVectorizer를 사용하여 텍스트를 토큰 수의 행렬로 변환
X = vectorizer.transform(documents)

# 코사인 유사도 계산
cosine_similarities = cosine_similarity(X)

# 유사도가 가장 높은 직무 포스팅 찾기
most_similar_job = documents[cosine_similarities[-1].argmax()]

# 결과 제공
print("가장 유사한 직무 포스팅: ", most_similar_job)

In [ ]:
# 상위 및 하위 10개의 유사도 값과 해당 직무 포스팅 찾기
top_similarities_indices = cosine_similarities[-1].argsort()[:-11:-1]
bottom_similarities_indices = cosine_similarities[-1].argsort()[:10]
top_similar_jobs = [(documents[idx], cosine_similarities[-1, idx]) for idx in top_similarities_indices]
bottom_similar_jobs = [(documents[idx], cosine_similarities[-1, idx]) for idx in bottom_similarities_indices]

# 상위 10개의 유사한 직무 포스팅 출력
print("상위 10개의 유사한 직무 포스팅:")
for i, (job, similarity) in enumerate(top_similar_jobs, start=1):
    print(f"{i}. 직무: {job}, 코사인 유사도: {similarity}")

# 하위 10개의 유사한 직무 포스팅 출력
print("\n하위 10개의 유사한 직무 포스팅:")
for i, (job, similarity) in enumerate(bottom_similar_jobs, start=1):
    print(f"{i}. 직무: {job}, 코사인 유사도: {similarity}")